<a href="https://colab.research.google.com/github/palak178/Machine-Learning/blob/main/Day4/Assignment4/Classification_Comparision_Nearest_Earth_Objects.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Importing the dataset

In [2]:
from sklearn.preprocessing import LabelEncoder
df = pd.read_csv('/content/nearestobj.csv')
df = df.drop(['orbiting_body', 'id', 'name', 'sentry_object'], 1)
le = LabelEncoder()
# df['sentry_object'] = le.fit_transform(df['sentry_object'])
df['hazardous'] = le.fit_transform(df['hazardous'])
# X = df.iloc[:,]
df.head()


/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (7,9) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  This is separate from the ipykernel package so we can avoid doing imports until


est_diameter_min  est_diameter_max  relative_velocity  miss_distance  \
0          1.198271          2.679415       13569.249224   5.483974e+07   
1          0.265800          0.594347       73588.726663   6.143813e+07   
2          0.722030          1.614507      114258.692129   4.979872e+07   
3          0.096506          0.215794       24764.303138   2.543497e+07   
4          0.255009          0.570217       42737.733765   4.627557e+07   

   absolute_magnitude  hazardous  
0               16.73          0  
1               20.00          1  
2               17.83          0  
3               22.20          0  
4               20.09          1

## Prep the data

In [3]:
X = df.iloc[:,:-1]
print(X)

       est_diameter_min  est_diameter_max  relative_velocity  miss_distance  \
0              1.198271          2.679415       13569.249224   5.483974e+07   
1              0.265800          0.594347       73588.726663   6.143813e+07   
2              0.722030          1.614507      114258.692129   4.979872e+07   
3              0.096506          0.215794       24764.303138   2.543497e+07   
4              0.255009          0.570217       42737.733765   4.627557e+07   
...                 ...               ...                ...            ...   
70282          0.025384          0.056760       27850.022452   4.313975e+06   
70283          0.017561          0.039268       37842.242799   4.933443e+07   
70284          0.056566          0.126485       51610.247668   4.876403e+07   
70285          0.016926          0.037848       28211.531276   2.464671e+07   
70286          0.139494          0.311918       57613.962429            NaN   

       absolute_magnitude  
0                   16.

In [4]:
y = df.iloc[:,-1]
print(y)

0        0
1        1
2        0
3        0
4        1
        ..
70282    0
70283    0
70284    0
70285    0
70286    2
Name: hazardous, Length: 70287, dtype: int64


In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 12)

In [7]:
print(X_train[:15])
print(X_test[:15])
print(y_train[:15])
print(y_test[:15])

       est_diameter_min  est_diameter_max  relative_velocity  miss_distance  \
48145          0.018389          0.041119       19330.269772   9.061849e+06   
37126          0.048368          0.108153       34632.324883   9.077583e+06   
60738          0.014607          0.032662       35313.530412   2.625727e+06   
21972          0.110804          0.247765       35879.081654   5.728649e+07   
61885          0.024466          0.054707       34475.715022   2.357121e+07   
13534          0.025384          0.056760       51991.584712   2.244721e+07   
21811          0.011080          0.024777       49281.496002   9.931567e+06   
43767          0.063761          0.142574        8258.296467   4.075503e+07   
13448          0.139494          0.311918       49040.638461   5.658126e+07   
49768          0.019256          0.043057       67326.686667   4.276326e+06   
12427          0.105817          0.236614       27508.900183   6.135455e+07   
50522          0.506471          1.132505       8120

# Feature scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train[:10])
print(X_test[:10])

[[-0.34222106 -0.34222106 -0.46142022 -1.56710517  0.75922628]
 [-0.34138979 -0.34138979  0.08850763  0.72532508  0.74887065]
 [-0.36374848 -0.36374848 -0.98512248 -0.96654484  1.0940582 ]
 [-0.38859811 -0.38859811 -1.11301825 -0.22225938  1.88108582]
 [-0.33853448 -0.33853448 -0.74139349 -1.38950524  0.71435189]
 [-0.38367888 -0.38367888 -0.4302476  -1.64112751  1.64635828]
 [ 0.75246062  0.75246062  0.92285154  0.17423576 -1.46032968]
 [-0.35158249 -0.35158249  0.74525861  1.33244437  0.88694567]
 [-0.35385055 -0.35385055 -0.01175174  0.11205101  0.92146443]
 [-0.3324138  -0.3324138  -0.01643598 -1.32351318  0.64531438]]
[[ 0.05761382  0.05761382  1.13616317 -0.66662661 -0.76995458]
 [-0.21038676 -0.21038676  0.12151961  0.56941061 -0.11409823]
 [-0.00168993 -0.00168993 -1.13610116  0.84000833 -0.66639831]
 [ 0.01717495  0.01717495 -0.37054944  0.08723965 -0.70091707]
 [-0.05653763 -0.05653763 -1.08630503  0.81001252 -0.5559383 ]
 [-0.34276889 -0.34276889  0.11420956  0.18240009  0.7

# Training the Logistic Regression model

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 10)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=10)

# Predicting the test set result

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.values.reshape(len(y_test),1)),1))
# y_pred.reshape(len(y_pred),1)
# y_test.values.reshape(len(y_test),1)

[[0 1]
 [0 0]
 [0 0]
 ...
 [0 0]
 [1 0]
 [0 0]]


# Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[20333   180]
 [ 2021   175]]


0.9030780747721168

# Training the SVM model using rbf kernel

In [ ]:
from sklearn.svm import SVC
classifier_svm = SVC(kernel = 'rbf', random_state = 0)
classifier_svm.fit(X_train, y_train)

SVC(random_state=0)

## Predicting the Test set results

In [ ]:
y_pred_svm = classifier_svm.predict(X_test)
print(np.concatenate((y_pred_svm.reshape(len(y_pred),1), y_test.values.reshape(len(y_test),1)),1))

[[0 1]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_svm)
print(cm)
accuracy_score(y_test, y_pred_svm)

[[20430    83]
 [ 1949   247]]


0.9105200581267339

# Training the SVM model using linear kernel

In [ ]:
from sklearn.svm import SVC
classifier_svm1 = SVC(kernel = 'linear', random_state = 0)
classifier_svm1.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

## Predicting the Test set results

In [ ]:
y_pred_svm1 = classifier_svm1.predict(X_test)
print(np.concatenate((y_pred_svm1.reshape(len(y_pred),1), y_test.values.reshape(len(y_test),1)),1))

[[0 1]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_svm1)
print(cm)
accuracy_score(y_test, y_pred_svm1)

[[20513     0]
 [ 2196     0]]


0.9032982517944428

# Training the SVM model using sigmoid kernel

In [ ]:
from sklearn.svm import SVC
classifier_svm3 = SVC(kernel = 'sigmoid', random_state = 0)
classifier_svm3.fit(X_train, y_train)

SVC(kernel='sigmoid', random_state=0)

## Predicting the Test set results

In [ ]:
y_pred_svm3 = classifier_svm3.predict(X_test)
print(np.concatenate((y_pred_svm3.reshape(len(y_pred),1), y_test.values.reshape(len(y_test),1)),1))

[[0 1]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_svm3)
print(cm)
accuracy_score(y_test, y_pred_svm3)

[[18700  1813]
 [ 1861   335]]


0.8382139239948919